---
products:

  opsman:
    product-version: "2.8.2"
    pivnet-product-slug: ops-manager
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "ops-manager-gcp-*.yml"

  # PAS
  pas:
    product-version: "2.8.3"
    pivnet-product-slug: elastic-runtime
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "srt-*.pivotal"
  pas-stemcell:
    product-version: "621.57"
    pivnet-product-slug: stemcells-ubuntu-xenial
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "light-bosh-stemcell-*-google-kvm-ubuntu-xenial-go_agent.tgz"

  pks:
    product-version: "1.6.1"
    pivnet-product-slug: pivotal-container-service
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "*.pivotal"
  pks-stemcell:
    product-version: "456.51"
    pivnet-product-slug: stemcells-ubuntu-xenial
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "light-bosh-stemcell-*-google-kvm-ubuntu-xenial-go_agent.tgz"

  wavefront-nozzle:
    product-version: 2.0.0
    pivnet-product-slug: wavefront-nozzle
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "wavefront-nozzle-*.pivotal"
    stemcell-iaas: google
  wavefront-nozzle-stemcell:
    product-version: "250.183"
    pivnet-product-slug: stemcells-ubuntu-xenial
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "light-bosh-stemcell-*-google-kvm-ubuntu-xenial-go_agent.tgz"

  pivotal-mysql:
    product-version: 2.7.5
    pivnet-product-slug: pivotal-mysql
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "pivotal-mysql-*.pivotal"
  pivotal-mysql-stemcell:
    product-version: "315.169"
    pivnet-product-slug: stemcells-ubuntu-xenial
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "light-bosh-stemcell-*-google-kvm-ubuntu-xenial-go_agent.tgz"

  p-rabbitmq:
    product-version: 1.18.3
    pivnet-product-slug: p-rabbitmq
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "p-rabbitmq-*.pivotal"
  p-rabbitmq-stemcell:
    product-version: "621.57"
    pivnet-product-slug: stemcells-ubuntu-xenial
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "light-bosh-stemcell-*-google-kvm-ubuntu-xenial-go_agent.tgz"

  p-spring-cloud-services:
    product-version: 3.1.5
    pivnet-product-slug: p-spring-cloud-services
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "p_spring-cloud-services-*.pivotal"
  p-spring-cloud-services-stemcell:
    product-version: "315.169"
    pivnet-product-slug: stemcells-ubuntu-xenial
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "light-bosh-stemcell-*-google-kvm-ubuntu-xenial-go_agent.tgz"